### PR TITLE
Add black code formatter

### PR DESCRIPTION
**Pull request by MartinHjelmare**
**Goal**
- Use black code formatter as the main style standard and style setter for the project. See https://github.com/python/black.

**Plan**
- This PR is step 1. Step 1 adds dev requirements and provides a set of config files for making black run smoothly. The imjoy package code has also been formatted with black. This creates a very big diff. Developers should run black before they commit changes, or at least before they make a PR to this repo. There are editor plugins for black for most popular editors.
- Step 2 is to add black as a CI check, using eg Travis CI. It will then run on PRs and make sure we keep the black formatting on the code base.

**Changes**
- Add black as lint requirement.
- Add dev requirements and update readme.
- Add setup.cfg and isort section.
- Add pre-commit-config for black. This can optionally be installed by developers by using [pre-commit](https://pre-commit.com/).
- Add flake8 config to setup.cfg.
- Format code with black.
- Manually break some really long lines.

**Relevant issue**
https://github.com/oeway/ImJoy/issues/92

### CODE REVIEW

**Comment by MartinHjelmare** [comment]
I've tested the engine after this change by running a small plugin in native python plugin mode:
```
<docs lang="markdown">
"Test the ImjoyEngine."
</docs>

<config lang="json">
{
  "name": "Sanity Test Plugin",
  "type": "native-python",
  "version": "0.1.0",
  "description": "Test the ImjoyEngine.",
  "tags": [],
  "ui": "",
  "cover": "",
  "inputs": null,
  "outputs": null,
  "flags": [],
  "icon": "extension",
  "api_version": "0.1.3",
  "env": "",
  "requirements": [],
  "dependencies": []
}
</config>

<script lang="python">
import numpy as np
class ImJoyPlugin():
    def setup(self):
        api.log('initialized')

    def run(self, ctx):
        api.alert('hello world.')

api.export(ImJoyPlugin())
</script>
```

**Comment by oeway** [comment]
I have just merged this.
If I run `black .` in the root folder of this project, it formats two extra files (imjoyWorkerTemplate.py and setup.py), is that normal?

**Comment by MartinHjelmare** [comment]
I didn't run on `setup.py`. I thought about it but then forgot about that.

The other file was changed when you merged master into this PR without running black again.

**Comment by oeway** [comment]
I see, so I will just merge #14 . The code looks prettier, we should add this to CI!

**Comment by oeway** [comment]
Should we add `pre-commit` to requirements_dev.txt ?

**Comment by MartinHjelmare** [comment]
Yes, we can do that. I didn't add it from the beginning since it's optional.

**Pull request merged**
