### PR TITLE
fix cors issue

### PR DESCRIPTION
**Pull request by oeway**
This fixes a cors error below:

`Access to fetch at 'http://127.0.0.1:9527/socket.io/?EIO=3&transport=polling&t=MnHng1h' from origin 'https://imjoy.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

### CODE REVIEW

**Comment by oeway** [comment]
@MartinHjelmare I don't know why the test failed, it also fails if I checkout the master branch, it seems something else changed. I checked our `requirements` we have every lib version fixed. Could you please take a look?

**Comment by MartinHjelmare** [comment]
`python-engineio` changed version from 3.8.2 in last successful build to 3.9.0 in this build. It's not pinned in `python-socketio`. So we need to pin it ourselves if we want total stability in that dependency too.

**Comment by MartinHjelmare** [comment]
Perhaps also check why that KeyError happens.

**Comment by oeway** [comment]
> `python-engineio` changed version from 3.8.2 in last successful build to 3.9.0 in this build. It's not pinned in `python-socketio`. So we need to pin it ourselves if we want total stability in that dependency too.

So you mean you can pass the test if you pin the version to 3.8.2?

**Comment by MartinHjelmare** [comment]
I don't know. I have just read the Travis logs and checked python-engineio recent version updates.

**Comment by oeway** [comment]
I just tried to fix the engineio version 3.8.2 and my local test still fails, no idea.

**Comment by MartinHjelmare** [comment]
https://github.com/oeway/ImJoy-Engine/pull/78#issuecomment-517655380

**Comment by oeway** [comment]
It works by pin python-engineio==3.8.2 now, strange that the master branch still has issue @MartinHjelmare 

The keyError is from python-engineio version, they changed something which cause this error.

**Comment by oeway** [comment]
@MartinHjelmare Thanks for your help!

**Pull request merged**
