### PR TITLE
Use snake case names

### PR DESCRIPTION
**Pull request by MartinHjelmare**
## Changes
- Make sure we use snake_case names for functions and variables.
- Make sure we follow PEP8 to not cause lint errors.
- Rename eng to engine.

@oeway Please check the module renaming, if those names are ok!

### CODE REVIEW

**Comment by oeway** [comment]
How about `eng` to `engine`, if it's not too long, try to use the full name? Did pep8 mention the naming?

**Comment by MartinHjelmare** [comment]
`pylint` linter (based on PEP8) complains if names are less than two characters for most things. I think there are some exceptions. Variables and functions should be snake_case.

**Comment by MartinHjelmare** [comment]
I don't really like `eng` since it sounds like short for `English`. But I used it since we use it so frequently. and then it's nice to have a short word. But we can change to engine.

**Comment by oeway** [comment]
Engine is not too long, requirements and environments as variable name and
use frequently will be too much.

But just for readability, i think it’s ok to make it a big longer.

**Comment by MartinHjelmare** [comment]
Can we merge here?

**Comment by oeway** [comment]
Sure, this is great improvement on the naming, thanks!

**Pull request merged**
